audit_header: false
title: Whissel Realty Real Estate Video Blog
description: 'Whissel Realty is a team of local real estate professionals committed to selling some of the most sought-after homes in San Diego. We are committed to helping you and your family build a secure future in the home of your dreams. As one of the top real estate teams in California, we have extensive knowledge of the real estate industry. With this podcast, we will provide some of the latest tips, trends, and market updates in order to help you achieve your real estate goals.'
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Joe Corbisiero
  about_markdown: >
    What makes Realtor Joe Corbisiero a unique real estate agent is his creative
    “Art of the Deal” ability to think outside the box and give scope to creative
    offers which have a very high acceptance rate.





    Realtor Joe Corbisiero like to negotiate prices and make things happen for
    his clients! The skills Joe has acquired have made even the most particular
    of his clients extremely satisfied.That is why almost all of Joe’s clients
    are returning clients and/or referrals.





    Realtor Joe Corbisiero understands how important the entire experience is for
    both to the buyer and seller. That’s only one of the many reasons Realtor Joe
    you through the entire process. This includes the art of finding the right
    deal for you.. Not just the perfect home.. But the right deal!'
  market: San Diego County
  license: 'CA BRE #01886351'
  brand: Whissel Realty
  brokerage:
  address: '3180 University Ave Suite 600<br>San Diego, CA 92104'
  phone: 760-201-9252
  email: joesellssandiego@gmail.com
  url: www.joesellssandiego.com
  first_CTA_text: Home Evaluation
  first_CTA_URL: 'http://joec.whisselrealty.com/home-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://joec.whisselrealty.com/results-map/'
  VR_form: 'http://oi.vresp.com?fid=cd24bb15c1'
welcome_headline: Get Educated About Real Estate
welcome_text_markdown: |
  Our mission at Whissel Realty is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/JoeSellsSanDiegocom-250353854985111/?fref=ts/'
  linkedin_url: 'https://www.linkedin.com/in/joesellssandiego/'
  gplus_url: 'https://plus.google.com/u/0/106555724969670868953'
  youtube_url: 'https://www.youtube.com/channel/UCOtLeMobPlvQqvB-3Uom0bg'
  twitter_url: 'https://twitter.com/JoeSellsSoCal'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Joe-Corbisiero/'
  trulia_url: 'https://www.trulia.com/profile/joe-corbisiero-agent-san-diego-ca-zg9l42nv/overview'
  yelp_url: 'https://www.yelp.com/biz/joe-corbisiero-whissel-realty-san-diego'
  podcast_url: 'https://itunes.apple.com/us/podcast/whissel-realty-real-estate/id1171929177?mt=2'
podcast:
  title: San Diego Real Estate Podcast with Joe Corbisiero
  categories: News & Politics
  image: /img/Corbisiero_Podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego County Area Real Estate Market'
  description: 'Whissel Realty is a team of local real estate professionals committed to selling some of the most sought-after homes in San Diego. We are committed to helping you and your family build a secure future in the home of your dreams. As one of the top real estate teams in California, we have extensive knowledge of the real estate industry. With this podcast, we will provide some of the latest tips, trends, and market updates in order to help you achieve your real estate goals.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Joe Corbisiero
images:
  client_headshot_path: /img/joe-c-headshot.jpg
  hero_logo_path: /img/logo_white.png
  hero_text: Real Estate Video Blog
  hero_background_hex: '#d13f1e'
  hero_image_path: /img/corbisiero_bkg.jpg
brand_color: '#f15c27'
theme_color: '#ffffff'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
